name: proyecto_dispositivos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  geolocator: ^9.0.2
  cloud_firestore: 5.6.5
  firebase_messaging: 15.2.4
  flutter_local_notifications: ^19.2.1
  gal: ^2.1.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  qr_flutter: ^4.1.0
  camera: ^0.11.0+1
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  local_auth: ^2.1.8
  qr_code_scanner_plus: 2.0.10+1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/IconoEco.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
