name: ecogo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  geolocator: ^14.0.0
  google_maps_flutter: ^2.2.0
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  camera: ^0.11.1
  image: ^4.5.4
  flutter_local_notifications: ^19.2.1
  firebase_messaging: ^15.2.6
  http: ^1.4.0
  qr: ^3.0.2
  path_provider: ^2.1.5
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  gal: ^2.3.1
  local_auth: ^2.3.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/